### ISSUE TITLE
Missing package on npm

### ISSUE THREAD

**Issue by equinusocio** [jonathantneal/postcss-register-property#1]
Hi @jonathantneal just to let you know that `postcss-register-property` is missing on npm and it returns 404.

**Comment by jonathantneal** [comment]
I was waiting for the spec to be real.

**Comment by equinusocio** [comment]
Ok this make sense, but don't you think is better add a disclaimer to tell this? :)

**Comment by jonathantneal** [comment]
Well, nobody noticed this repository for months until I tweeted it a half hour ago, and I’ve published it, so I’m okay with the 30 minutes of ambiguity. 😄

**Comment by equinusocio** [comment]
I knew this repo and i tweeted about it time ago :) but never tried it until now.

**Comment by equinusocio** [comment]
@jonathantneal Do you know where to find all the syntax types or we must wait the spec?
